/**
 * Shared TypeScript types and interfaces
 */

import type { ExamType, DifficultyLevel, QuestionType, SubscriptionPlan } from '../utils/constants';

// Database types (will be auto-generated by Supabase)
export interface Database {
  public: {
    Tables: {
      // Define your table types here
      // These will match your Supabase schema
    };
  };
}

// User related types
export interface User {
  id: string;
  email: string;
  full_name: string | null;
  avatar_url: string | null;
  subscription_plan: SubscriptionPlan;
  created_at: string;
  updated_at: string;
}

// Question related types
export interface Question {
  id: string;
  exam_type: ExamType;
  difficulty: DifficultyLevel;
  question_type: QuestionType;
  question_text: string;
  options: string[] | null;
  correct_answer: string;
  explanation: string | null;
  topic: string;
  subtopic: string | null;
  created_at: string;
  updated_at: string;
}

// Exam session types
export interface ExamSession {
  id: string;
  user_id: string;
  exam_type: ExamType;
  started_at: string;
  completed_at: string | null;
  score: number | null;
  total_questions: number;
}

// Answer submission types
export interface AnswerSubmission {
  id: string;
  session_id: string;
  question_id: string;
  user_answer: string;
  is_correct: boolean;
  time_spent: number; // in seconds
  created_at: string;
}

// API Response types
export interface ApiResponse<T> {
  data: T | null;
  error: string | null;
  message?: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    page: number;
    page_size: number;
    total: number;
    total_pages: number;
  };
}

// Form types
export interface LoginFormData {
  email: string;
  password: string;
}

export interface RegisterFormData {
  email: string;
  password: string;
  full_name: string;
}

export interface QuestionFilters {
  exam_type?: ExamType;
  difficulty?: DifficultyLevel;
  topic?: string;
  question_type?: QuestionType;
}
